---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse
    tag: 'latest'
           
inputs:
- name: cfcr-git


params:
  DIRECTOR_NAME:
  CFCR_MASTER_DNS:

run:
  path: cfcr-git/tasks/fetch-token/task.sh
