- type: replace
  path: /releases/-
  value: 
    name: "bosh-dns"
    version: "1.10.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.10.0"
    sha1: "d1aadbda5d60c44dec4a429cda872cf64f6d8d0b"
